name: flutter_vto_project
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
    

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  animated_splash_screen: ^1.3.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.6



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/product1.jpg
    - assets/images/product2.jpg
    - assets/images/product3.jpg
    - assets/images/product4.jpg
    - assets/images/product5.jpg
    - assets/images/product6.jpg
